language: python

sudo: required

services:
  - docker

before_install:
  - docker-compose build


script:
  - docker-compose run --rm uwsgi-server python manage.py test

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose push

# Read about amazon Elastic Container Service(ECS)


#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: ""
#  bucket_name: ""
#  bucket_path: ""
#  on:
#    branch: master
#
#  access_key_id: $AWS_ACCESS_KEY_ID
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
