language: python

sudo: required

services:
  - docker

before_install:
  - docker-compose build


script:
  - docker-compose run --rm uwsgi_server python manage.py test

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose push

