version: "3"

services:
  uwsgi_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    image: "miladkhodabandehloo/docker_bug_uwsgi_server"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "test"]

  nginx:
    build:
      context: .
      dockerfile: nginxDockerfile
    depends_on:
      - uwsgi_server
    ports:
    - 80:80
    restart: always
    image: "miladkhodabandehloo/docker_bug_nginx"